name: Go

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "master" ]

jobs:
  Test:
    name: Test Go Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install gcc libgl1-mesa-dev xorg-dev

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Install test dependencies
      run: go install github.com/jstemmer/go-junit-report@latest

    - name: Test
      run: go test -v 2>&1 ./... | tee | go-junit-report -set-exit-code > report.xml

    - name: Publish Test Summary
      uses: test-summary/action@v2
      with:
        paths: report.xml
      if: always()

  Lint:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  Release:
    needs: [Test, Lint]
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Github Tag Bump
      uses: anothrNick/github-tag-action@1.67.0
      id: tag-version
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Create Release
      run: GOPROXY=proxy.golang.org go list -m github.com/michael-ryan/cellularautomata@${{ steps.tag-version.outputs.new_tag }}
